table 'Démo CALCULATE'
	lineageTag: d5cbf8df-3aae-4cda-a0ed-7772c1bc05f8

	measure 'Ajout Filtre Produit 7' = CALCULATE( [# Transactions], Produits[Produit] = "Produit 7" )
		formatString: 0
		lineageTag: 7d686c99-da8f-471b-a929-059ab5b8f8bf

	measure 'Modif Filtre Apollo' = CALCULATE( [# Transactions], KEEPFILTERS( Clients[Client] = "Apollo SARL" ) )
		formatString: 0
		lineageTag: 4ebcfb49-39fa-4fd9-b04f-caccc41fdbcb

	measure 'ALL Transactions Client' = CALCULATE( [# Transactions], ALL( Clients[Client] ) )
		formatString: 0
		lineageTag: e92c3968-5b50-4b17-888c-e57ad56f2369

	measure 'Combinaison Filtre' = CALCULATE( [# Transactions], Produits[Produit] = "Produit 7", Clients[Client] = "Apollo SARL" )
		formatString: 0
		lineageTag: 0773c0e8-5c85-489a-9d76-289d683b5604

	measure '% Transaction Client' = DIVIDE( [# Transactions], [ALL Transactions Client], 0 )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: b915ea61-7375-4f59-b52c-18f095c592c4

	partition 'Démo CALCULATE-6506b4c2-a849-44cd-b3ed-521454c5a23f' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#"Colonne 1" = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Colonne 1", type text}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"Colonne 1"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

